import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import useSWR from 'swr';
const fetcher = (url) => fetch(url).then((res) => res.json());

const IndexPage = (props) => {
  const { data, error, isLoading } = useSWR('https://jsonplaceholder.typicode.com/todos/1', fetcher)
  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>
  return (
    <>
      <Head>
        <title>hello bro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <li key={data.id}>
          {" "}
          {data.id} : {data.title}
        </li>
      
    </>
  );
};

export default IndexPage;
