import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

// export async function getServerSideProps({ params }) {
//   console.log("params----", params);
//   let data = null;
//   let resp = null;
//   resp = await fetch(`https://jsonplaceholder.typicode.com/todos/${params.id}`);

//   data = await resp?.json();
//   console.log("type of data ", typeof data);
//   console.log("data");
//   return {
//     props: {
//       todos: data,
//     },
//   };
// }


export async function getStaticProps() {
  
  let data = null;
  let resp = null;
  resp = await fetch(`https://jsonplaceholder.typicode.com/todos/1`);

  data = await resp?.json();
  console.log("type of data ", typeof data);
  console.log("data");
  return {
    props: {
      todos: data,
    },
  };
}

const IndexPage = (props) => {
  const { todos } = props;
  // const router = useRouter();
  // const { id } = router.query;
  return (
    <>
      <Head>
        <title>hello bro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <li key={todos.id}>
          {" "}
          {todos.id} : {todos.title}
        </li>
      
    </>
  );
};

export default IndexPage;
